#!/usr/bin/env bash
./build.sh
VERSION=$(./tarball/quota-export/quota-export --version | awk '{print $3}')
docker build --tag wekasolutions/quota-export:latest --tag wekasolutions/quota-export:$VERSION .
#docker build --tag wekasolutions/quota-export:$VERSION .
